#SPDX-License-Identifier: MIT-0
---
# defaults file for mediawiki_1
mediawiki_server_name: mediawiki-1
mediawiki_server_url: "http://{{ hostvars[groups['nginx_lb'][0]].private_ip }}"

mediawiki_site_name: "Company Wiki"
mediawiki_admin_user: "wikiadmin"
mediawiki_admin_password: "wikiadminpassword"

mediawiki_language: "ru"

mediawiki_db_type: "postgres"
mediawiki_db_host: "{{ hostvars[groups['db_primary'][0]].private_ip }}"
mediawiki_db_port: "{{ postgres_port }}"
mediawiki_db_name: "{{ wiki_db }}"
mediawiki_db_user: "{{ wiki_user }}"
mediawiki_db_password: "{{ wiki_password }}"

mediawiki_archive_path: /tmp/mediawiki.tar.gz
mediawiki_extract_parent: /var/www
mediawiki_release_dir: "/var/www/mediawiki-{{ mediawiki_version }}"

php_fpm_service: php8.1-fpm
php_fpm_socket: /run/php/php8.1-fpm.sock

mediawiki_run_installer: true
